# Generated by Django 4.0.3 on 2022-03-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='username1',
        ),
    ]
