# Generated by Django 4.0.3 on 2022-03-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitsOfDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_min', models.DateField()),
                ('old_max', models.DateField()),
                ('new_min', models.DateField()),
                ('new_max', models.DateField()),
            ],
        ),
    ]
