# Generated by Django 4.0.3 on 2022-03-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_limitsofdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pappers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
