# Generated by Django 4.0.3 on 2022-03-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_remove_moving_available_remove_passport_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username1',
            new_name='username',
        ),
    ]
