# Generated by Django 4.0.3 on 2022-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_rename_username1_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='internal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passport',
            name='normal',
            field=models.IntegerField(),
        ),
    ]
